### ISSUE TITLE
Support for playback of already started stream

### ISSUE THREAD

**Issue by waclaw66** [matijagaspar/ws-avc-player#8]
Hello.
Would it be possible to support playback of already started h264 live stream?
Currently the playback works only when a h264 stream is played from the very begining.
Maybe encapsulation to MPEG-TS or MP4 could help to proper demuxing.
Explanation:
I have developed a simple websocket server which handles various live streams from webcams and recompress them to mpeg1/mpeg-ts streams (using ffmpeg pipe) and sends them to clients via websocket. I use JSMpeg player on client side, it reconnects well to already started mpeg-ts streams, unfortunatelly mpeg1 doesn't provide required quality with low bitrate.
Thus I search for the h264 alternative. Your player looks promissing, but it cannot handle playback from random start point in the middle of a h264 stream.

Thanks.

**Comment by matijagaspar** [comment]
The player supports playing a already started stream, but because how h264 works it will have to wait for a pps (key frame) packet to start (usually few seconds, depending on the encoder settings) . The default example (one with listen on 5000 for stream) does just that, you can start a sream and connect the client at any point. 

Regarding encapsulation, this project aim was to get rid of as much delay as possible over websocket. Encapsulation would either add additional delay or impact the client cpu usage and increase size even more. Websocket already provides most of the things anyway (packet order, packet encapsulation,...).

If latency is not a priority you could always use the html native video element for playback. It supports various codes and encapsulations, there are a couple of projects doing it like this, but delays are between 5-10sec.

**Comment by waclaw66** [comment]
My priority was minimal latency. I'll try to set key frame interval of h264 as less as possible, hope it helps. I was using default settings of ffmpeg h264 encoder before, that could be the reason why playback didn't start. When there is a support of playing already started stream, there must be a problem on my side. Thanks.

**Comment by waclaw66** [comment]
@matijagaspar 
I investigated what is wrong with my encoder. The answer is simple. I supposed that ws-avc-player can play raw h264 stream sent via websocket (like jsmpeg player). That's a mistake. H264 stream is processed by server.js and split by NAL separator into messages with some json headers. My server is written in python, I have to imitate this functionality as well. Just for clarification for others.
A simple description of this message format would be helpfull.

**Comment by matijagaspar** [comment]
Yes, that's right. I did NAL splitting on server to lessen the burden on client, since it already does the decoding on the cpu.

I will put this note to the readme
